name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  # Create GitHub Release
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      release_id: ${{ steps.create_release.outputs.id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        run: |
          if [ -f CHANGELOG.md ]; then
            echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
            sed -n "/## \[${{ steps.get_version.outputs.VERSION }}\]/,/## \[/p" CHANGELOG.md | sed '$d' >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "CHANGELOG=Release ${{ steps.get_version.outputs.VERSION }}" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          name: FrameSense ${{ steps.get_version.outputs.VERSION }}
          body: |
            ${{ steps.changelog.outputs.CHANGELOG }}
            
            ## Downloads
            - **Windows**: Download the `.msi` installer
            - **macOS**: Download the `.dmg` file  

            
            ## Installation
            Download and install the appropriate version for your platform.
          draft: false
          prerelease: ${{ contains(steps.get_version.outputs.VERSION, '-') }}

  # Build and upload release assets
  build-release:
    name: Build Release
    needs: create-release
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: windows-x64
            asset_name: framesense-windows-x64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: macos-x64
            asset_name: framesense-macos-x64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: macos-arm64
            asset_name: framesense-macos-arm64
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install frontend dependencies
        run: |
          npm config set registry https://registry.npmjs.org/
          npm ci --retry=3 --timeout=60000

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: release-${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build Tauri app
        run: npm run build:tauri -- --target ${{ matrix.target }}

      # Upload different file types based on OS

      - name: Upload Windows MSI
        if: matrix.os == 'windows-latest'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: src-tauri/target/${{ matrix.target }}/release/bundle/msi/frame-sense_*.msi

      - name: Upload macOS DMG
        if: matrix.os == 'macos-latest'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: src-tauri/target/${{ matrix.target }}/release/bundle/dmg/frame-sense_*.dmg

      # Generate updater artifacts for Tauri updater
      - name: Upload updater artifacts
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            src-tauri/target/${{ matrix.target }}/release/bundle/*/frame-sense_*.tar.gz
            src-tauri/target/${{ matrix.target }}/release/bundle/*/frame-sense_*.tar.gz.sig
  # Notify release
  notify:
    name: Notify Release
    needs: [create-release, build-release]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Notify Discord
        if: success()
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            🚀 **FrameSense ${{ steps.get_version.outputs.VERSION }} Released!**
            
            📱 **Desktop Apps**: Available for Windows and macOS
            📦 **Download**: https://github.com/${{ github.repository }}/releases/tag/${{ steps.get_version.outputs.VERSION }}

      - name: Notify Slack
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: success
          text: |
            ✅ FrameSense ${{ steps.get_version.outputs.VERSION }} has been released!
            Download: https://github.com/${{ github.repository }}/releases/tag/${{ steps.get_version.outputs.VERSION }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}